// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Jz8rr1jIhyPCGQYOO9n4d8yFlcQJcp4',
    appId: '1:1084545859311:web:0813f226ef4c2d500aa51a',
    messagingSenderId: '1084545859311',
    projectId: 'animeapp-6a3ed',
    authDomain: 'animeapp-6a3ed.firebaseapp.com',
    storageBucket: 'animeapp-6a3ed.firebasestorage.app',
    measurementId: 'G-QN8WWB16FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1KofLaP10hF0RT9wCCsKyLqDbgOB9TEU',
    appId: '1:1084545859311:android:a9417d1c1dba6d430aa51a',
    messagingSenderId: '1084545859311',
    projectId: 'animeapp-6a3ed',
    storageBucket: 'animeapp-6a3ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-d4vN4D8MI6wJ4qDO0_g9_J78qtqIWh8',
    appId: '1:1084545859311:ios:d96f87dbb51408360aa51a',
    messagingSenderId: '1084545859311',
    projectId: 'animeapp-6a3ed',
    storageBucket: 'animeapp-6a3ed.firebasestorage.app',
    iosBundleId: 'com.your.anihub',
  );
}
